### ISSUE TITLE
关于使用dq的问题请教

### ISSUE THREAD

**Issue by xhochipe** [tal-tech/go-queue#10]
在如下场景中:
  比如我查询的记录是  A  B C 三条
  这时候我把A B C 三条记录循环依次调用Delay()存到beanstalk中,然后我在处理A,B,C更新逻辑,这时候假如A,B更新正常,C更新失败,我想把C从beanstalk删除,不希望C被消费,这时候怎么删除，我看了下暴露的api里面好像没有这么的操作

**Comment by kevwan** [comment]
Revoke

**Comment by xhochipe** [comment]
> Revoke
已经看源码找到了，
@kevwan  谢谢啦，
